package InputForm;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

public class InputForm1 {

	@Test
void TestGoogle() throws Exception { 
		
		// Initiating the browser.
		ChromeDriver CD = new ChromeDriver();
		
		// To maximize the browser once it is launched.
		CD.manage().window().maximize();
		
		// Opening particular link - via get or navigate
		// get does not maintain history but navigate does.
		CD.get("http://demo.seleniumeasy.com/input-form-demo.html");
		//CD.navigate().to("https://google.com");
		
		// One of the example where we are using simple name locator
		WebElement first_name = CD.findElement(By.name("first_name"));
		first_name.sendKeys("Sunil");
		
		// Another example where we are using xpath locator generated by system itself.
		WebElement last_name = CD.findElement(By.xpath("//*[@id=\"contact_form\"]/fieldset/div[2]/div/div/input"));
		last_name.sendKeys("Siddharth");
		
		// close - Will close the only active browser window, will not close the pop up generated due to the opened window.
		// quit - Will close all the browsers generated due to parent opened browser.
		CD.close();
		
	}
}
